# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='total_hours',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
